# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-01 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empowerment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
        ),
        migrations.CreateModel(
            name='EmpowermentBeneficiary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('full_name', models.CharField(max_length=150)),
                ('ward', models.CharField(max_length=50)),
                ('trade', models.CharField(max_length=50)),
                ('item', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('empowerment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scholarships.Empowerment')),
            ],
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
        ),
        migrations.CreateModel(
            name='ScholarshipBeneficiary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('institution', models.CharField(blank=True, max_length=500, null=True)),
                ('institution_type', models.CharField(choices=[('UNI', 'university'), ('POL', 'polytechnic'), ('NUR', 'School of Nursing'), ('COE', 'College of Education')], max_length=3)),
                ('course', models.CharField(max_length=200)),
                ('level', models.IntegerField()),
                ('matric_number', models.CharField(blank=True, max_length=20, null=True)),
                ('scholarship_type', models.CharField(choices=[('PM', 'permanent'), ('BS', 'bursary')], max_length=2)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scholarships.Scholarship')),
            ],
        ),
    ]
