# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-03 21:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empowermentbeneficiary',
            name='empowerment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaries', to='scholarships.Empowerment'),
        ),
        migrations.AlterField(
            model_name='scholarshipbeneficiary',
            name='scholarship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaries', to='scholarships.Scholarship'),
        ),
    ]
