# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-02 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(upload_to='img/event'),
        ),
        migrations.AlterField(
            model_name='eventgallery',
            name='pics',
            field=models.ImageField(upload_to='img/event'),
        ),
    ]
