# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-06 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20180406_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pics', models.ImageField(upload_to='static/img/event')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_gallery', to='events.Event')),
            ],
        ),
    ]
