# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-06 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_eventgallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventgallery',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
